name: EpicRPGFishing
version: 2.0.0-Alpha
main: me.Vark123.EpicRPGFishing.Main
author: Vark123
depend: [MythicMobs,NBTAPI,WorldGuard,MultiWorld]
api-version: 1.16

commands:
  epicfishing:
    aliases: [efishing, erpgfishing, fishing]