name: EpicRPGFishing
version: 2.0.1
main: me.Vark123.EpicRPGFishing.Main
author: Vark123
depend: [MythicMobs,NBTAPI,WorldGuard,MultiWorld]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5

commands:
  epicfishing:
    aliases: [efishing, erpgfishing, fishing]
  epicrodupgrade:
    aliases: [eru, efru]
  tanalorrmerchant:
    aliases: [tanmerchant, tanmerch]